# Generated by Django 2.2.7 on 2021-01-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('orderid', models.CharField(db_column='OrderID', max_length=5, primary_key=True, serialize=False)),
                ('restaurantid', models.CharField(db_column='RestaurantID', max_length=5)),
                ('userid', models.CharField(db_column='UserID', max_length=5)),
                ('addresstodelivery', models.CharField(db_column='AddressToDelivery', max_length=50)),
                ('deliveryfee', models.DecimalField(db_column='DeliveryFee', decimal_places=0, max_digits=2)),
                ('status', models.CharField(db_column='Status', max_length=10)),
                ('reasonofreject', models.CharField(db_column='ReasonOfReject', max_length=20)),
                ('riderid', models.CharField(db_column='RiderID', max_length=5)),
            ],
            options={
                'db_table': 'orderitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('orderid', models.CharField(db_column='OrderID', max_length=5, primary_key=True, serialize=False)),
                ('productid', models.CharField(db_column='ProductID', max_length=5)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=0, max_digits=2)),
            ],
            options={
                'db_table': 'orderproduct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.CharField(db_column='ProductID', max_length=5, primary_key=True, serialize=False)),
                ('restaurantid', models.CharField(db_column='RestaurantID', max_length=5)),
                ('productname', models.CharField(db_column='ProductName', max_length=20)),
                ('productprice', models.DecimalField(db_column='ProductPrice', decimal_places=0, max_digits=2)),
                ('productpic', models.CharField(db_column='ProductPic', max_length=10)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantid', models.CharField(db_column='RestaurantID', max_length=5, primary_key=True, serialize=False)),
                ('restaurantname', models.CharField(db_column='RestaurantName', max_length=25)),
                ('description', models.CharField(db_column='Description', max_length=150)),
                ('contactnum', models.CharField(db_column='ContactNum', max_length=11)),
                ('address', models.CharField(db_column='Address', max_length=50)),
                ('image', models.CharField(db_column='Image', max_length=10)),
            ],
            options={
                'db_table': 'restaurant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.CharField(db_column='ReviewID', max_length=5, primary_key=True, serialize=False)),
                ('productid', models.CharField(db_column='ProductID', max_length=5)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comment', models.CharField(db_column='Comment', max_length=25)),
                ('username', models.CharField(db_column='UserName', max_length=25)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
    ]
