# Generated by Django 2.2.7 on 2021-01-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_orderitem_orderproduct_product_restaurant_review'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
