# Generated by Django 2.2.7 on 2021-01-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210114_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='orderproductid',
            field=models.AutoField(db_column='ID', default=1, primary_key=True, serialize=False),
        ),
    ]
