# Generated by Django 2.2.7 on 2021-01-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210114_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='orderproductid',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='productid',
            field=models.AutoField(db_column='ProductID', primary_key=True, serialize=False),
        ),
    ]
